CREATE VIEW USER_HC AS
SELECT DISTINCT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, 
	H.HOMETOWN_CITY_ID
FROM USERS U
LEFT JOIN USER_HOMETOWN_CITY H ON H.USER_ID = U.USER_ID;

CREATE VIEW USER_HC_CITY AS
SELECT DISTINCT A.USER_ID, A.FIRST_NAME, A.LAST_NAME, A.YEAR_OF_BIRTH, A.MONTH_OF_BIRTH, A.DAY_OF_BIRTH, A.GENDER, 
	C.CITY_NAME AS HOMETOWN_CITY, C.STATE_NAME AS HOMETOWN_STATE, C.COUNTRY_NAME AS HOMETOWN_COUNTRY
FROM USER_HC A
LEFT JOIN CITIES C ON A.HOMETOWN_CITY_ID = C.CITY_ID;

CREATE VIEW USER_CC AS
SELECT DISTINCT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, 
	C.CURRENT_CITY_ID
FROM USERS U
LEFT JOIN USER_CURRENT_CITY C ON C.USER_ID = U.USER_ID;

CREATE VIEW USER_CC_CITY AS
SELECT DISTINCT A.USER_ID, A.FIRST_NAME, A.LAST_NAME, A.YEAR_OF_BIRTH, A.MONTH_OF_BIRTH, A.DAY_OF_BIRTH, A.GENDER, 
	C.CITY_NAME AS CURRENT_CITY, C.STATE_NAME AS CURRENT_STATE, C.COUNTRY_NAME AS CURRENT_COUNTRY
FROM USER_CC A
LEFT JOIN CITIES C ON A.CURRENT_CITY_ID = C.CITY_ID;

CREATE VIEW USER_BOTH_CITY AS
SELECT DISTINCT A.USER_ID, A.FIRST_NAME, A.LAST_NAME, A.YEAR_OF_BIRTH, A.MONTH_OF_BIRTH, A.DAY_OF_BIRTH, A.GENDER, A.HOMETOWN_CITY, A.HOMETOWN_STATE, A.HOMETOWN_COUNTRY,
B.CURRENT_CITY, B.CURRENT_STATE, B.CURRENT_COUNTRY 
FROM USER_HC_CITY A
FULL JOIN USER_CC_CITY B ON A.USER_ID = B.USER_ID;

CREATE VIEW EP AS
SELECT DISTINCT E.USER_ID, E.PROGRAM_YEAR, 
	P.INSTITUTION, P.CONCENTRATION, P.DEGREE
FROM EDUCATION E
LEFT JOIN  PROGRAMS P ON E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW VIEW_USER_INFORMATION AS
SELECT DISTINCT cast(A.USER_ID AS VARCHAR2(100)) AS USER_ID, A.FIRST_NAME, A.LAST_NAME, cast(A.YEAR_OF_BIRTH AS NUMBER) AS YEAR_OF_BIRTH, cast(A.MONTH_OF_BIRTH AS NUMBER) AS MONTH_OF_BIRTH, cast(A.DAY_OF_BIRTH AS NUMBER) AS DAY_OF_BIRTH, A.GENDER,  A.CURRENT_CITY, A.CURRENT_STATE, A.CURRENT_COUNTRY, A.HOMETOWN_CITY, A.HOMETOWN_STATE, A.HOMETOWN_COUNTRY,
	B.INSTITUTION AS INSTUTUTION_NAME, cast(B.PROGRAM_YEAR AS NUMBER(38)) AS PROGRAM_YEAR, cast(B.CONCENTRATION AS CHAR(100)) AS PROGRAM_CONCENTRATION, B.DEGREE AS PROGRAM_DEGREE
FROM USER_BOTH_CITY A
LEFT JOIN EP B ON A.USER_ID = B.USER_ID;

----------------------------------------------------------------------------------------------
CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT DISTINCT cast(USER1_ID AS VARCHAR2(100)) AS USER1_ID, cast(USER2_ID AS VARCHAR2(100)) AS USER2_ID
FROM FRIENDS;
----------------------------------------------------------------------------------------------

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT DISTINCT A.ALBUM_ID, cast(A.ALBUM_OWNER_ID AS VARCHAR2(100)) AS OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, cast(A.ALBUM_CREATED_TIME AS TIMESTAMP(6)) AS ALUBM_CREATED_TIME, cast(A.ALBUM_MODIFIED_TIME AS TIMESTAMP(6)) AS ALBUM_MODIFIED_TIME, cast(A.ALBUM_LINK AS VARCHAR2(2000)) AS ALBUM_LINK, A.ALBUM_VISIBILITY, 
	P.PHOTO_ID, cast(P.PHOTO_CAPTION AS VARCHAR2(2000)) AS PHOTO_CAPTION, cast(P.PHOTO_CREATED_TIME AS TIMESTAMP(6)) AS PHOTO_CREATED_TIME, cast(P.PHOTO_MODIFIED_TIME AS TIMESTAMP(6)) AS PHOTO_MODIFIED_TIME, cast(P.PHOTO_LINK AS VARCHAR2(2000)) AS PHOTO_LINK
FROM PHOTOS P
LEFT JOIN ALBUMS A ON P.ALBUM_ID = A.ALBUM_ID;
----------------------------------------------------------------------------------------------
CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT DISTINCT TAG_PHOTO_ID AS PHOTO_ID, cast(TAG_SUBJECT_ID AS VARCHAR2(100)) AS TAG_SUBJECT_ID, cast(TAG_CREATED_TIME AS TIMESTAMP(6)) AS TAG_CREATED_TIME, TAG_X AS TAG_X_COORDINATE, TAG_Y AS TAG_Y_COORDINATE
FROM TAGS;
----------------------------------------------------------------------------------------------
CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT DISTINCT cast(E.EVENT_ID AS VARCHAR2(100)) AS EVENT_ID, cast(E.EVENT_CREATOR_ID AS VARCHAR2(100)) AS EVENT_CREATOR_ID, E.EVENT_NAME, cast(E.EVENT_TAGLINE AS VARCHAR2(1000)) AS EVENT_TAGLINE, cast(E.EVENT_DESCRIPTION AS VARCHAR2(4000)) AS EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, cast(E.EVENT_LOCATION AS VARCHAR2(200)) AS EVENT_LOCATION, 
	C.CITY_NAME AS EVENT_CITY, C.STATE_NAME AS EVENT_STATE, C.COUNTRY_NAME AS EVENT_COUNTRY, cast(E.EVENT_START_TIME AS TIMESTAMP(6)) AS EVENT_START_TIME, cast(E.EVENT_END_TIME AS TIMESTAMP(6)) AS EVENT_END_TIME
FROM USER_EVENTS E
LEFT JOIN CITIES C ON E.EVENT_CITY_ID = C.CITY_ID;





